spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  profiles:
    active: "@spring.profiles.active@"

files:
  dataFiles: Material
  coordFiles: coor