spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  profiles:
    active: "@spring.profiles.active@"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/admin
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true